# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.location.slideshare.user:
        bundle_name: "campaignchain/location-slideshare"
        module_identifier: "campaignchain-slideshare-user"

services:
#    campaign_chain_location_slide_share.example:
#        class: CampaignChain\Location\SlideShareBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
